/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.MainController;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import models.CacheParameters;

/**
 *
 * @author Rafael
 */
public class MainView extends javax.swing.JFrame {
    
    private MainController controller;
    private JFileChooser fChooser;

    /**
     * Creates new form InterfacePrincipal
     *
     * @param cont
     */
    public MainView(MainController cont, String mat[][], boolean ll) {
        this.controller = cont;
        this.fChooser = new JFileChooser();
        
        initComponents();
        if(ll){
            ll2.setText("LL");
        }
        this.preencheDados(mat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1d = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        l1t = new javax.swing.JLabel();
        l1a = new javax.swing.JLabel();
        l1b = new javax.swing.JLabel();
        l1s = new javax.swing.JLabel();
        l1dc = new javax.swing.JTextField();
        l1do = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        ll2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        l2t = new javax.swing.JLabel();
        l2a = new javax.swing.JLabel();
        l2b = new javax.swing.JLabel();
        l2s = new javax.swing.JLabel();
        l2c = new javax.swing.JTextField();
        l2o = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        l1it = new javax.swing.JLabel();
        l1ia = new javax.swing.JLabel();
        l1ib = new javax.swing.JLabel();
        l1is = new javax.swing.JLabel();
        l1ic = new javax.swing.JTextField();
        l1io = new javax.swing.JButton();
        calc = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cache Energy Sim");

        l1d.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("L1 - Data");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        l1t.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l1t.setText("Type:");

        l1a.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l1a.setText("Assoc:");

        l1b.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l1b.setText("Block Size:");

        l1s.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l1s.setText("Size:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l1t)
                    .addComponent(l1a)
                    .addComponent(l1b)
                    .addComponent(l1s))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l1t)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l1s)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l1b)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l1a)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        l1dc.setEditable(false);
        l1dc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l1dcActionPerformed(evt);
            }
        });

        l1do.setText("Open Memory File");
        l1do.setEnabled(false);
        l1do.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l1doActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout l1dLayout = new javax.swing.GroupLayout(l1d);
        l1d.setLayout(l1dLayout);
        l1dLayout.setHorizontalGroup(
            l1dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(l1dLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addGap(50, 50, 50)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(l1dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l1dc)
                    .addComponent(l1do, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        l1dLayout.setVerticalGroup(
            l1dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(l1dLayout.createSequentialGroup()
                .addGroup(l1dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(l1dLayout.createSequentialGroup()
                        .addGroup(l1dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(l1dLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel6))
                            .addGroup(l1dLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(l1dc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(l1do)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, l1dLayout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ll2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ll2.setText("L2");

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        l2t.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l2t.setText("Type:");

        l2a.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l2a.setText("Assoc:");

        l2b.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l2b.setText("Block Size:");

        l2s.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l2s.setText("Size:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l2t)
                    .addComponent(l2a)
                    .addComponent(l2b)
                    .addComponent(l2s))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l2t)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l2s)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l2b)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l2a)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        l2c.setEditable(false);
        l2c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l2cActionPerformed(evt);
            }
        });

        l2o.setText("Open Memory File");
        l2o.setEnabled(false);
        l2o.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l2oActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ll2)
                .addGap(71, 71, 71)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l2o, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2c, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(l2c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(l2o)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ll2)
                .addGap(51, 51, 51))
        );

        jPanel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel46.setText("L1 - Instruction");

        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        l1it.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l1it.setText("Type:");

        l1ia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l1ia.setText("Assoc:");

        l1ib.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l1ib.setText("Block Size:");

        l1is.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l1is.setText("Size:");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l1it)
                    .addComponent(l1ia)
                    .addComponent(l1ib)
                    .addComponent(l1is))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l1it)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l1is)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l1ib)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l1ia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        l1ic.setEditable(false);
        l1ic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l1icActionPerformed(evt);
            }
        });

        l1io.setText("Open Memory File");
        l1io.setEnabled(false);
        l1io.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l1ioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel46)
                .addGap(24, 24, 24)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l1ic, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l1io, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(l1ic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(l1io))
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel46)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        calc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        calc.setText("Calcular");
        calc.setEnabled(false);
        calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(calc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l1d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(l1d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(calc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void l2cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l2cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l2cActionPerformed

    private void l1icActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l1icActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l1icActionPerformed

    private void l1ioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l1ioActionPerformed
        l1ic.setText(controller.escArquivoL1I());
        l2o.setEnabled(true);
       
    }//GEN-LAST:event_l1ioActionPerformed

    private void l2oActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l2oActionPerformed
        l2c.setText(controller.escArquivoL2());
        calc.setEnabled(true);
    }//GEN-LAST:event_l2oActionPerformed

    private void l1doActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l1doActionPerformed
        l1dc.setText(controller.escArquivoL1D());
        
        l1io.setEnabled(true);
    }//GEN-LAST:event_l1doActionPerformed

    private void l1dcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l1dcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l1dcActionPerformed

    private void calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcActionPerformed
        
        new FinalView(controller.returnEnergy(), controller).setVisible(true);
    }//GEN-LAST:event_calcActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calc;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel l1a;
    private javax.swing.JLabel l1b;
    public javax.swing.JPanel l1d;
    private javax.swing.JTextField l1dc;
    private javax.swing.JButton l1do;
    private javax.swing.JLabel l1ia;
    private javax.swing.JLabel l1ib;
    private javax.swing.JTextField l1ic;
    private javax.swing.JButton l1io;
    private javax.swing.JLabel l1is;
    private javax.swing.JLabel l1it;
    private javax.swing.JLabel l1s;
    private javax.swing.JLabel l1t;
    private javax.swing.JLabel l2a;
    private javax.swing.JLabel l2b;
    private javax.swing.JTextField l2c;
    private javax.swing.JButton l2o;
    private javax.swing.JLabel l2s;
    private javax.swing.JLabel l2t;
    private javax.swing.JLabel ll2;
    // End of variables declaration//GEN-END:variables

    public int showFileChooserDialog(FileNameExtensionFilter filtro) {
        fChooser.setAcceptAllFileFilterUsed(false);
        fChooser.addChoosableFileFilter(filtro);
        int r = fChooser.showOpenDialog(MainView.this);
        fChooser.removeChoosableFileFilter(filtro);
        return r;
    }
    public int showFileSaveDialog(FileNameExtensionFilter filtro){
        fChooser.setAcceptAllFileFilterUsed(false);
        fChooser.addChoosableFileFilter(filtro);
        int r = fChooser.showSaveDialog(MainView.this);
        fChooser.removeChoosableFileFilter(filtro);
        return r;
    }
    
    
    public File getSelectedFile() {
        return fChooser.getSelectedFile();
    }
    
    public void manssageDialog(String s) {
        JOptionPane.showMessageDialog(this, s);
    }
    
    public void preencheDados(String mat[][]) {
        if (mat.length >= 1) {
            l1t.setText("Type: " + mat[0][0]);
            l1s.setText("Size: " + mat[0][1]);
            l1b.setText("Block Size: " + mat[0][2]);
            l1a.setText("Assoc: " + mat[0][3]);
            l1dc.setEnabled(true);
            l1do.setEnabled(true);
            if (mat.length >= 2) {
                l1it.setText("Type: " + mat[1][0]);
                l1is.setText("Size: " + mat[1][1]);
                l1ib.setText("Block Size: " + mat[1][2]);
                l1ia.setText("Assoc: " + mat[1][3]);
                l1ic.setEnabled(true);
                if (mat.length >= 3) {
                    l2t.setText("Type: " + mat[2][0]);
                    l2s.setText("Size: " + mat[2][1]);
                    l2b.setText("Block Size: " + mat[2][2]);
                    l2a.setText("Assoc: " + mat[2][3]);
                    l2c.setEnabled(true);
                    
                }
            }
        }
    }
}
